###  Задание 10.1
Чем отличается тип данных int8 от uint8?
- int8 содержит 0 среди возможных значений
- int8 позволяет сохранить в два раза меньше различных чисел
- int8 включает в себя отрицательные числа
- Максимальное число, которое можно сохранить, — 128 

<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code>
 int8 включает в себя отрицательные числа
</code>
</details>

###   Задание 10.2
Переменная num задана следующим образом: num = "-65536". Можно ли положить её в массив чисел типа int16 без потери точности?
- Да, можно
- Нельзя, поскольку это строка
- Нельзя, поскольку число отрицательное
- Нельзя, так как выделено недостаточно памяти для сохранения числа целиком 

<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code> - Нельзя, так как выделено недостаточно памяти для сохранения числа целиком <br>
 Число превратится в другое число, отличное от того, что было изначально, поскольку памяти для сохранения числа целиком не хватит (минимальное число в int16 — -32768).
</code>
</details>

In [2]:
import numpy as np

In [4]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

###    Задание 10.3
В чём преимущество массивов по сравнению со списками?
- Массивы позволяют хранить объекты разных типов одновременно
- Массивы обладают ограниченной длиной
- Массивы позволяют получать элементы по индексу за одинаковое время
- Массивы могут быть вложенными друг в друга 

<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code> 
    - Массивы позволяют получать элементы по индексу за одинаковое время
</code>
</details>

###    Задание 10.4
Какие способы позволяют достоверно сравнить переменную elem с числом np.nan?

Отметьте все подходящие варианты ответов.
- elem == np.nan

- elem == None

- np.isnan(elem)

- elem is np.nan 
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code> 
C Эта функция вернёт True, если в переменной будет лежать np.nan. <br>
D np.nan можно сравнивать друг с другом (а точнее, проверять объекты на эквивалентность) с помощью оператора is.
</code>
</details>

###    Задание 10.5
Получите сумму чисел, сохранённых в переменных x и y.
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code> 
print(np.int64(x)+np.int64(y))
</code>
</details>

###   Задание 10.6 
Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание: воспользуйтесь функцией zeros из библиотеки numpy, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

Напоминание: в Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.
Пример:
<pre>
<code>
get_chess(1)
# array([[0.]])
get_chess(4)
# array([[0., 1., 0., 1.],
#        [1., 0., 1., 0.],
#        [0., 1., 0., 1.],
#        [1., 0., 1., 0.]])
</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp;
<pre>
<code>
import numpy as np

def get_chess(a):
    new_array = np.zeros((a, a))
    new_array[::2,1::2] = 1
    new_array[1::2,::2] = 1
    return new_array

print(get_chess(5))
</code>
</details>

In [11]:
import numpy as np


def get_chess(a):
    new_array = np.zeros((a, a))
    new_array[::2,1::2] = 1
    new_array[1::2,::2] = 1
    return new_array

print(get_chess(5))

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


###   Задание 10.7
Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

Пример:
<pre>
<code>
array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)
</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; <code> 
import numpy as np
<pre>
<code>
def shuffle_seed(arr):
    seed = np.random.randint(0, 2**32)
    np.random.seed(seed)
    return np.random.permutation(arr), seed
</code>
</details>

In [13]:
def shuffle_seed(arr):
    seed = np.random.randint(0, 2**32)
    np.random.seed(seed)
    return np.random.permutation(arr), seed
array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)


(array([2, 3, 1, 4, 5]), 1428937871)

###   Задание 10.8 
Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

Пример:
<pre>
<code>
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)
</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; 
<pre>
<code>
import numpy as np


def min_max_dist(*vectors):
    if vectors:
        vector1 = vectors[0]
    min_dist = min(np.linalg.norm(vector1 - vec) for vec in vectors[1:])
    max_dist = max(np.linalg.norm(vector1 - vec) for vec in vectors[1:])
    return min_dist, max_dist

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
</code>
</details>

In [1]:
import numpy as np


def min_max_dist(*vectors):
    if vectors:
        vector1 = vectors[0]
    min_dist = min(np.linalg.norm(vector1 - vec) for vec in vectors[1:])
    max_dist = max(np.linalg.norm(vector1 - vec) for vec in vectors[1:])
    return min_dist, max_dist

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)


(5.196152422706632, 10.392304845413264)

###  Задание 10.9
Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

Пример:
<pre>
<code>
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
# True
</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; 
<pre>
<code>import numpy as np


def any_normal(*vectors):
    flag = not all(np.dot(vectors[0], vector) for vector in vectors[1:])
    return flag
</code>
</details>

In [2]:
import numpy as np


def any_normal(*vectors):
    flag = not all(np.dot(vectors[0], vector) for vector in vectors[1:])
    return flag

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
# True

True


###  Задание 10.10
Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

Результат:
<pre>
<code>
get_loto(3)
array([[[ 35,  66,  38,  11,  32],
       [ 32,   7,  37,  83,  42],
       [ 89,  37,  19,  51,  89],
       [ 70, 100,  83,   5,  11],
       [ 20,  13,  60,  26,  41]],
 
      [[ 23,  49,  76,  44,  43],
       [ 59,  63,  99,  92,   2],
       [ 83,   4,  25,  73,  19],
       [ 10,  18,  40,  11,  21],
       [ 58,  45,  73,  93,  61]],
 
      [[100,  88,  70,  34,  51],
       [  5,  35,  36,  85,  88],
       [ 72,  23,  87,  30,  40],
       [ 29,  21,  51,  73,  81],
       [ 91,  19,  87,  60,  27]]])
</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; 
<pre>
<code>import numpy as np


def get_loto(num):
    arr = np.random.randint(1, 101, size= (num, 5, 5))
    return arr
</code>
</details>

In [3]:
import numpy as np


def get_loto(num):
    arr = np.random.randint(1, 101, size= (num, 5, 5))
    return arr



array([[[69, 99, 45, 40, 93],
        [56, 76, 20,  7, 59],
        [74, 78,  8,  8, 12],
        [63, 30, 42, 62, 91],
        [82, 40, 52, 81, 13]],

       [[63, 33, 44, 32, 99],
        [ 9, 19, 84, 63,  4],
        [86, 48, 45, 27, 23],
        [ 2, 68, 87, 34, 51],
        [23,  3, 86, 23,  7]],

       [[24, 82, 31, 53, 16],
        [93, 90, 64, 33, 79],
        [63, 27, 71, 95, 34],
        [96,  8, 81, 86, 33],
        [62, 34, 22,  6, 54]]])

### Задание 10.11 
Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

Пример:
<pre>
<code>
get_unique_loto(3)

Результат:

array([[[26, 91, 73,  7, 16],
       [46, 85, 78, 77, 51],
       [84, 86, 55, 71, 58],
       [17, 61, 50, 30, 97],
       [66, 29, 38, 41, 32]],
 
      [[49, 32,  3, 21, 85],
       [45,  8, 94, 46, 96],
       [41, 38, 58, 37, 98],
       [66, 77, 54, 80, 26],
       [62, 63, 72,  5, 43]],
 
      [[55, 60,  6, 80, 97],
       [23, 69, 94,  9, 24],
       [17, 98, 27, 63, 79],
       [84, 74, 51, 39, 54],
       [77, 30, 48, 75, 85]]])

</code>
</pre>
<details>
<summary><strong>Show answer</strong> (Click Here)</summary>
    &emsp; &emsp; 
<pre>
<code>import numpy as np
def get_unique_loto(num):
    nums = np.arange(1,101)
    arr = np.zeros((num, 5, 5), dtype=np.int32)
    for i in range(num):
        arr[i] = np.random.choice(nums, size=(5, 5), replace=False)
    return arr
</code>
</details>

In [23]:
import numpy as np


# #My solution:
# def get_unique_loto(num):
#     nums = np.arange(1,101)
#     arr = np.zeros((num, 5, 5), dtype=np.int32)
#     for i in range(num):
#         arr[i] = np.random.choice(nums, size=(5, 5), replace=False)
#     return arr
#Recommended solution
def get_unique_loto(num):
    nums = np.arange(1,101)
    arr = list()
    for i in range(num):
        arr.append(np.random.choice(nums, size=(5, 5), replace=False))
    arr = np.array(arr)
    return arr

get_unique_loto(3)

array([[[ 99,   1,  96,   7,  97],
        [ 53,  56,  27,  50,   8],
        [ 46,  85,   9,  40,  69],
        [ 98,  22,  43,  30,  24],
        [ 49,  19,  32,  39,  12]],

       [[ 82,  73,  10,   8,  60],
        [ 23,  18,  40,  54,  33],
        [ 27,  70,  36,  52,  84],
        [ 17,  95,  80, 100,  92],
        [  4,  46,  38,  94,  45]],

       [[ 16,  41,  46,  72,  54],
        [ 52,  97,  28,  49,  94],
        [ 76,  67,  56,  57,   1],
        [ 33,  60,  98, 100,  24],
        [  2,  31,  37,  80,   3]]])